export const WS_CONNECTION = 'WS_CONNECTION';
export const WS_MESSAGE = 'WS_MESSAGE';
export const WS_DISCONNECT = 'WS_DISCONNECT';
export const UDP_CREATE = 'UDP_CREATE';
export const UDP_MESSAGE = 'UDP_MESSAGE';

export const ADMIN_WS_CREATED = 'ADMIN_WS_CREATED';
export const ADMIN_CONNECTION = 'ADMIN_CONNECTION';
export const ADMIN_START_GAME = 'ADMIN_START_GAME';

export const ADD_PLAYER = 'ADD_PLAYER';
export const REMOVE_PLAYER = 'REMOVE_PLAYER';
export const RESET_PLAYER = 'RESET_PLAYER';
export const PLAYER_STATE_UPDATE = 'PLAYER_STATE_UPDATE';
export const FIRST_PLAYER_HIDDEN = 'FIRST_PLAYER_HIDDEN';
export const LAST_PLAYER_HIDDEN = 'LAST_PLAYER_HIDDEN';
export const REQUEST_START_GAME = 'REQUEST_START_GAME';
export const START_GAME = 'START_GAME';
