export const WS_CONNECTION = 'WS_CONNECTION';
export const WS_MESSAGE = 'WS_MESSAGE';
export const WS_DISCONNECT = 'WS_DISCONNECT';
export const UDP_CREATE = 'UDP_CREATE';
export const UDP_MESSAGE = 'UDP_MESSAGE';

export const ADD_PLAYER = 'ADD_PLAYER';
export const REMOVE_PLAYER = 'REMOVE_PLAYER';
export const PLAYER_STATE_UPDATE = 'PLAYER_STATE_UPDATE';
